/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swing;

import java.awt.Cursor;
import java.awt.Point;
import java.awt.event.WindowEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Enumeration;
import java.util.List;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractButton;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author ren
 */
public class HotelBookingSystem extends javax.swing.JFrame {

    private Hotel[] hotels;
    private List<Booking> bookings;
    private int bookingNow;
    private Date today;

    /**
     * Creates new form HotelBookingSystem
     */
    public HotelBookingSystem() {
        String todayString = getDate((new Date()));
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        try {
            today = sdf.parse(todayString);
        } catch (ParseException ex) {
            Logger.getLogger(HotelBookingSystem.class.getName()).log(Level.SEVERE, null, ex);
        }
        bookingNow = 0;
        Hotel hotel1 = new Hotel("/img/GreenHotel.png", "Green Hotel", "Green Street", 98, "/img/singleRoom.png", 5, "/img/doubleRoom.png", 2, "/img/standardRoom.png", 1);
        Hotel hotel2 = new Hotel("/img/WhiteHotel.png", "White Hotel", "White Street", 92, "/img/singleRoom2.png", 2, "/img/doubleRoom2.png", 4, "/img/standardRoom2.png", 0);
        hotels = new Hotel[]{hotel1, hotel2};
        bookings = new ArrayList<Booking>();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toolBarBtnGroup = new javax.swing.ButtonGroup();
        RoomTypeBtnGroup = new javax.swing.ButtonGroup();
        navigationBar = new javax.swing.JPanel();
        BookingBtn = new javax.swing.JButton();
        reservationBtn = new javax.swing.JButton();
        helpBtn = new javax.swing.JButton();
        ExitBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        dateLabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        hotelPanel = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        titleLabel = new javax.swing.JLabel();
        mapLabel = new javax.swing.JLabel();
        showImageLabel = new javax.swing.JLabel();
        showNameLabel = new javax.swing.JLabel();
        noteLabel = new javax.swing.JLabel();
        hotelDetailPanel = new javax.swing.JPanel();
        hotelImageLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        room3Label = new javax.swing.JLabel();
        room1Label = new javax.swing.JLabel();
        room2Label = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        bookBtn = new javax.swing.JButton();
        hotelNameLabel = new javax.swing.JLabel();
        hotelAddressLabel = new javax.swing.JLabel();
        favorableRateLabel = new javax.swing.JLabel();
        bookPanel = new javax.swing.JPanel();
        bookPanel.setVisible(false);
        jLabel2 = new javax.swing.JLabel();
        selectedHotelLabel = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        selectedAddressLabel = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        singleRoomBtn = new javax.swing.JRadioButton();
        doubleRoomBtn = new javax.swing.JRadioButton();
        standardRoomBtn = new javax.swing.JRadioButton();
        room1Num = new javax.swing.JLabel();
        room2Num = new javax.swing.JLabel();
        room3Num = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        roomNumComboBox = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        peopleNumComboBox = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        bookerNameField = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        phoneNumField = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        startMonthBox = new javax.swing.JComboBox<>();
        startDayBox = new javax.swing.JComboBox<>();
        startYearBox = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        endYearBox = new javax.swing.JComboBox<>();
        endMonthBox = new javax.swing.JComboBox<>();
        endDayBox = new javax.swing.JComboBox<>();
        bookNowBtn = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();
        Discard = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        myReservationPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        bookingInfoList = new javax.swing.JList<>();
        removeBtn = new javax.swing.JButton();
        totalBookingNumLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hotel Booking System");
        setResizable(false);
        setSize(new java.awt.Dimension(1260, 931));

        navigationBar.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        BookingBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BookingBtn.setText("Booking");
        BookingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookingBtnActionPerformed(evt);
            }
        });

        reservationBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        reservationBtn.setText("My Reservation");
        reservationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservationBtnActionPerformed(evt);
            }
        });

        helpBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        helpBtn.setText("Help");
        helpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpBtnActionPerformed(evt);
            }
        });

        ExitBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ExitBtn.setText("Exit");
        ExitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Today is:");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jSeparator1.setFont(new java.awt.Font("宋体", 3, 15)); // NOI18N

        dateLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dateLabel.setText(getDate());

        jLabel10.setFont(new java.awt.Font("SWGothg", 3, 48)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(111, 193, 204));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Hotel");

        jLabel11.setFont(new java.awt.Font("SWGothg", 0, 48)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(111, 193, 204));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Booking");

        jLabel12.setFont(new java.awt.Font("SWGothg", 0, 48)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(111, 193, 204));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("System");

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N

        javax.swing.GroupLayout navigationBarLayout = new javax.swing.GroupLayout(navigationBar);
        navigationBar.setLayout(navigationBarLayout);
        navigationBarLayout.setHorizontalGroup(
            navigationBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navigationBarLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(navigationBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ExitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(helpBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BookingBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(reservationBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE))
                .addGap(25, 25, 25))
            .addGroup(navigationBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navigationBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navigationBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(navigationBarLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(navigationBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(navigationBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        navigationBarLayout.setVerticalGroup(
            navigationBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navigationBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BookingBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(reservationBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(helpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ExitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        BookingBtn.getAccessibleContext().setAccessibleDescription("");

        hotelPanel.setPreferredSize(new java.awt.Dimension(1045, 873));

        titleLabel.setFont(new java.awt.Font("SWItalt", 3, 36)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(111, 193, 204));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Booking");
        titleLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        mapLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mapLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mapGreen.png"))); // NOI18N
        mapLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        mapLabel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                mapLabelMouseMoved(evt);
            }
        });
        mapLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mapLabelMouseClicked(evt);
            }
        });

        showImageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        showNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        noteLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        noteLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        noteLabel.setText("(Select a hotel on the map)");

        hotelDetailPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hotel Detail", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("SWItalt", 3, 24), new java.awt.Color(111, 193, 204))); // NOI18N

        hotelImageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hotelImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource(hotels[0].getHotelImg())));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Hotel Name:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Hotel Address:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Room type");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Favorable rate:");

        room3Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        room3Label.setIcon(new javax.swing.ImageIcon(getClass().getResource(hotels[0].getRoom3Img())));

        room1Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        room1Label.setIcon(new javax.swing.ImageIcon(getClass().getResource(hotels[0].getRoom1Img())));

        room2Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        room2Label.setIcon(new javax.swing.ImageIcon(getClass().getResource(hotels[0].getRoom2Img())));
        room2Label.setPreferredSize(new java.awt.Dimension(170, 170));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Single Room");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Double Room");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Standard Room");

        bookBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bookBtn.setText("Book Now");
        bookBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookBtnActionPerformed(evt);
            }
        });

        hotelNameLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        hotelNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hotelNameLabel.setText(hotels[0].getName());

        hotelAddressLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        hotelAddressLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hotelAddressLabel.setText(hotels[0].getAddress());

        favorableRateLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        favorableRateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        favorableRateLabel.setText(hotels[0].getFavorableRate()+"%");

        javax.swing.GroupLayout hotelDetailPanelLayout = new javax.swing.GroupLayout(hotelDetailPanel);
        hotelDetailPanel.setLayout(hotelDetailPanelLayout);
        hotelDetailPanelLayout.setHorizontalGroup(
            hotelDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hotelDetailPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(hotelDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(hotelDetailPanelLayout.createSequentialGroup()
                        .addGroup(hotelDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(room1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(hotelDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bookBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(room2Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(hotelDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(room3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8))
                    .addGroup(hotelDetailPanelLayout.createSequentialGroup()
                        .addGroup(hotelDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(hotelDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hotelAddressLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hotelNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(favorableRateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hotelDetailPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(hotelImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(186, 186, 186))
        );
        hotelDetailPanelLayout.setVerticalGroup(
            hotelDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hotelDetailPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hotelImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(hotelDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(hotelNameLabel))
                .addGap(23, 23, 23)
                .addGroup(hotelDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(hotelAddressLabel))
                .addGap(23, 23, 23)
                .addGroup(hotelDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(favorableRateLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(hotelDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(hotelDetailPanelLayout.createSequentialGroup()
                        .addGroup(hotelDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(room1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(room2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(hotelDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addGroup(hotelDetailPanelLayout.createSequentialGroup()
                        .addComponent(room3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)))
                .addGap(34, 34, 34)
                .addComponent(bookBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        hotelDetailPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel3, jLabel4, jLabel5, jLabel6});

        bookPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Booking Detail", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("SWItalt", 3, 24), new java.awt.Color(111, 193, 204))); // NOI18N
        bookPanel.setPreferredSize(new java.awt.Dimension(586, 786));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Hotel Name:");

        selectedHotelLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        selectedHotelLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Hotel Address:");

        selectedAddressLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        selectedAddressLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Room Type:");

        RoomTypeBtnGroup.add(singleRoomBtn);
        singleRoomBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        singleRoomBtn.setText("Single Room");
        singleRoomBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                singleRoomBtnActionPerformed(evt);
            }
        });

        RoomTypeBtnGroup.add(doubleRoomBtn);
        doubleRoomBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        doubleRoomBtn.setText("Double Room");
        doubleRoomBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doubleRoomBtnActionPerformed(evt);
            }
        });

        RoomTypeBtnGroup.add(standardRoomBtn);
        standardRoomBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        standardRoomBtn.setText("Standard Room");
        standardRoomBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                standardRoomBtnActionPerformed(evt);
            }
        });

        room1Num.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Number of Room:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Left");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Left");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Left");

        peopleNumComboBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        peopleNumComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("Number of People:");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText("Booker Name:");

        bookerNameField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bookerNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookerNameFieldActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel21.setText("Phone Number:");

        phoneNumField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        phoneNumField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNumFieldActionPerformed(evt);
            }
        });
        phoneNumField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                phoneNumFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                phoneNumFieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                phoneNumFieldKeyTyped(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel22.setText("Start Date:");

        startMonthBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        startMonthBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Month", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        startMonthBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                startMonthBoxItemStateChanged(evt);
            }
        });

        startDayBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        startDayBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Day" }));
        startDayBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startDayBoxActionPerformed(evt);
            }
        });

        startYearBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        startYearBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year", "2021", "2022" }));
        startYearBox.setSelectedIndex(1);

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel23.setText("End Date:");

        endYearBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        endYearBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year", "2021", "2022" }));
        endYearBox.setSelectedIndex(1);
        endYearBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endYearBoxActionPerformed(evt);
            }
        });

        endMonthBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        endMonthBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Month", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        endMonthBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                endMonthBoxItemStateChanged(evt);
            }
        });

        endDayBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        endDayBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Day" }));
        endDayBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endDayBoxActionPerformed(evt);
            }
        });

        bookNowBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bookNowBtn.setText("Submit");
        bookNowBtn.setPreferredSize(new java.awt.Dimension(141, 31));
        bookNowBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookNowBtnActionPerformed(evt);
            }
        });

        resetBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        resetBtn.setText("Reset");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });

        Discard.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Discard.setText("Discard");
        Discard.setPreferredSize(new java.awt.Dimension(141, 40));
        Discard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiscardActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setText("(11 digits)");

        javax.swing.GroupLayout bookPanelLayout = new javax.swing.GroupLayout(bookPanel);
        bookPanel.setLayout(bookPanelLayout);
        bookPanelLayout.setHorizontalGroup(
            bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(bookPanelLayout.createSequentialGroup()
                        .addGroup(bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bookPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(bookPanelLayout.createSequentialGroup()
                                        .addGroup(bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(standardRoomBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(doubleRoomBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(singleRoomBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(room2Num, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(room3Num, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(room1Num, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING))))
                                    .addGroup(bookPanelLayout.createSequentialGroup()
                                        .addGroup(bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(endYearBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 69, Short.MAX_VALUE)
                                            .addComponent(startYearBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(peopleNumComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(roomNumComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(bookPanelLayout.createSequentialGroup()
                                                .addComponent(startMonthBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(startDayBox, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(bookPanelLayout.createSequentialGroup()
                                                .addComponent(endMonthBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(endDayBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                    .addGroup(bookPanelLayout.createSequentialGroup()
                                        .addComponent(phoneNumField, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel25))
                                    .addComponent(bookerNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(17, 17, 17))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bookPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(selectedHotelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(bookPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(selectedAddressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(bookPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(resetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bookNowBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Discard, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(56, 56, 56))
        );

        bookPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel17, jLabel18});

        bookPanelLayout.setVerticalGroup(
            bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectedHotelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectedAddressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(singleRoomBtn)
                    .addComponent(room1Num, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(room2Num, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(doubleRoomBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(standardRoomBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(room3Num, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(roomNumComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(peopleNumComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startMonthBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startDayBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startYearBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(endYearBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(endMonthBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(endDayBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bookerNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(phoneNumField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel25)))
                .addGap(49, 49, 49)
                .addGroup(bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bookPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(resetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bookNowBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Discard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        bookPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {doubleRoomBtn, singleRoomBtn, standardRoomBtn});

        bookPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel16, jLabel17, jLabel18});

        bookPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {room1Num, room2Num, room3Num});

        myReservationPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Reservation Detail", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("SWItalt", 3, 24), new java.awt.Color(111, 193, 204))); // NOI18N
        myReservationPanel.setPreferredSize(new java.awt.Dimension(1000, 0));

        bookingInfoList.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jScrollPane2.setViewportView(bookingInfoList);

        removeBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        removeBtn.setText("Remove");
        removeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBtnActionPerformed(evt);
            }
        });

        totalBookingNumLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        totalBookingNumLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalBookingNumLabel.setText("totalBookingNumLabel");

        javax.swing.GroupLayout myReservationPanelLayout = new javax.swing.GroupLayout(myReservationPanel);
        myReservationPanel.setLayout(myReservationPanelLayout);
        myReservationPanelLayout.setHorizontalGroup(
            myReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, myReservationPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(removeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(308, 308, 308))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, myReservationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(myReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(totalBookingNumLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 749, Short.MAX_VALUE))
                .addContainerGap())
        );
        myReservationPanelLayout.setVerticalGroup(
            myReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myReservationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addGap(18, 18, 18)
                .addComponent(removeBtn)
                .addGap(18, 18, 18)
                .addComponent(totalBookingNumLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout hotelPanelLayout = new javax.swing.GroupLayout(hotelPanel);
        hotelPanel.setLayout(hotelPanelLayout);
        hotelPanelLayout.setHorizontalGroup(
            hotelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(hotelPanelLayout.createSequentialGroup()
                .addGroup(hotelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(hotelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(showNameLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(hotelPanelLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(noteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(hotelPanelLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(showImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(hotelPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(mapLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hotelDetailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bookPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(myReservationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 789, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(hotelPanelLayout.createSequentialGroup()
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 1009, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        hotelPanelLayout.setVerticalGroup(
            hotelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hotelPanelLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(hotelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(hotelPanelLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(mapLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(noteLabel)
                        .addGap(18, 18, 18)
                        .addComponent(showImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(showNameLabel))
                    .addComponent(hotelDetailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bookPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
                    .addComponent(myReservationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );

        mapLabel.getAccessibleContext().setAccessibleName("mapLabel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(navigationBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(hotelPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 2431, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(navigationBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(hotelPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 917, Short.MAX_VALUE)
                .addContainerGap())
        );

        hotelPanel.getAccessibleContext().setAccessibleParent(BookingBtn);
    }// </editor-fold>//GEN-END:initComponents

    private void BookingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookingBtnActionPerformed
        if (bookingNow == 1) {
            titleLabel.setText("Booking");
            hotelDetailPanel.setVisible(false);
            bookPanel.setVisible(true);
            mapLabel.setVisible(true);
            noteLabel.setVisible(true);
            showImageLabel.setVisible(true);
            showNameLabel.setVisible(true);
            myReservationPanel.setVisible(false);
        } else {
            titleLabel.setText("Booking");
            hotelDetailPanel.setVisible(true);
            bookPanel.setVisible(true);
            mapLabel.setVisible(true);
            noteLabel.setVisible(true);
            showImageLabel.setVisible(true);
            showNameLabel.setVisible(true);
            myReservationPanel.setVisible(false);
        }
    }//GEN-LAST:event_BookingBtnActionPerformed

    private void reservationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservationBtnActionPerformed
        titleLabel.setText("My Reservation");
        hotelDetailPanel.setVisible(false);
        bookPanel.setVisible(false);
        mapLabel.setVisible(false);
        noteLabel.setVisible(false);
        showImageLabel.setVisible(false);
        showNameLabel.setVisible(false);
        myReservationPanel.setVisible(true);
        if (bookings.size() == 0) {
            totalBookingNumLabel.setText("You have no booking now");
            removeBtn.setEnabled(false);
        } else {
            totalBookingNumLabel.setText("You have " + bookings.size() + " booking totally");
            removeBtn.setEnabled(true);
            DefaultListModel defaultListModel = new DefaultListModel();
            for (int i = 0; i < bookings.size(); i++) {
                defaultListModel.add(i, bookings.get(i).toString());
            }
            bookingInfoList.setModel(defaultListModel);
        }

    }//GEN-LAST:event_reservationBtnActionPerformed

    private void helpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpBtnActionPerformed
        JOptionPane.showMessageDialog(this, "Welecome to the hotel booking system.\nYou can view the hotels on \"Booking\" page and make bookings.\nYou can view your reservations on \"My Reservation\" page.\nFeel free to leave the system at any time by clicking the \"Exit\" button.", "Help", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_helpBtnActionPerformed

    private void ExitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBtnActionPerformed
        int quitVal = JOptionPane.showConfirmDialog(this, "Do you want to quit?", "Notice", JOptionPane.YES_NO_OPTION);
        if (quitVal == 0) {
            System.out.println("Bye");
            System.exit(0);
        }
        if (quitVal == 1) {
            System.out.println("Stay");
        }
    }//GEN-LAST:event_ExitBtnActionPerformed

    private void bookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookBtnActionPerformed
        this.bookingNow = 1;
        int bookDecision = JOptionPane.showConfirmDialog(this, "Do you want to book \"" + hotelNameLabel.getText() + "\"?", "Notice", JOptionPane.YES_NO_OPTION);
        if (bookDecision == 0) {
            hotelDetailPanel.setVisible(false);
            bookPanel.setVisible(true);
            selectedHotelLabel.setText(hotelNameLabel.getText());
            selectedAddressLabel.setText(hotelAddressLabel.getText());
            if (hotelNameLabel.getText().equals(hotels[0].getName())) {
                if (hotels[0].getRoom1Num() == 0) {
                    singleRoomBtn.setEnabled(false);
                    room1Num.setText("No room");
                } else {
                    room1Num.setText(String.valueOf(hotels[0].getRoom1Num()));
                }
                if (hotels[0].getRoom2Num() == 0) {
                    doubleRoomBtn.setEnabled(false);
                    room2Num.setText("No room");
                } else {
                    room2Num.setText(String.valueOf(hotels[0].getRoom2Num()));
                }
                if (hotels[0].getRoom3Num() == 0) {
                    standardRoomBtn.setEnabled(false);
                    room3Num.setText("No room");
                } else {
                    room3Num.setText(String.valueOf(hotels[0].getRoom3Num()));
                }
            } else {

                if (hotels[1].getRoom1Num() == 0) {
                    singleRoomBtn.setEnabled(false);
                    room1Num.setText("No room");
                } else {
                    room1Num.setText(String.valueOf(hotels[1].getRoom1Num()));
                }
                if (hotels[1].getRoom2Num() == 0) {
                    doubleRoomBtn.setEnabled(false);
                    room2Num.setText("No room");
                } else {
                    room2Num.setText(String.valueOf(hotels[1].getRoom2Num()));
                }
                if (hotels[1].getRoom3Num() == 0) {
                    standardRoomBtn.setEnabled(false);
                    room3Num.setText("No room");
                } else {
                    room3Num.setText(String.valueOf(hotels[1].getRoom3Num()));
                }
            }

        }
        if (bookDecision == 1) {
            System.out.println("Another look");
        }

    }//GEN-LAST:event_bookBtnActionPerformed

    private void singleRoomBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_singleRoomBtnActionPerformed
        int totalRoomNum = Integer.parseInt(room1Num.getText());

        String[] comboBoxItems = new String[totalRoomNum];
        for (int i = 0; i < totalRoomNum; i++) {
            comboBoxItems[i] = String.valueOf(i + 1);
        }
        roomNumComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(comboBoxItems));
    }//GEN-LAST:event_singleRoomBtnActionPerformed

    private void doubleRoomBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doubleRoomBtnActionPerformed
        int totalRoomNum = Integer.parseInt(room2Num.getText());
        String[] comboBoxItems = new String[totalRoomNum];
        for (int i = 0; i < totalRoomNum; i++) {
            comboBoxItems[i] = String.valueOf(i + 1);
        }
        roomNumComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(comboBoxItems));
    }//GEN-LAST:event_doubleRoomBtnActionPerformed

    private void standardRoomBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_standardRoomBtnActionPerformed
        int totalRoomNum = Integer.parseInt(room3Num.getText());
        String[] comboBoxItems = new String[totalRoomNum];
        for (int i = 0; i < totalRoomNum; i++) {
            comboBoxItems[i] = String.valueOf(i + 1);
        }
        roomNumComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(comboBoxItems));
    }//GEN-LAST:event_standardRoomBtnActionPerformed

    private void bookerNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookerNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookerNameFieldActionPerformed

    private void phoneNumFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNumFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneNumFieldActionPerformed

    private void startDayBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startDayBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startDayBoxActionPerformed

    private void endYearBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endYearBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_endYearBoxActionPerformed

    private void endDayBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endDayBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_endDayBoxActionPerformed

    private void phoneNumFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneNumFieldKeyReleased
        String value = phoneNumField.getText();
        phoneNumField.setText(value.replaceAll("[^\\d]", ""));
    }//GEN-LAST:event_phoneNumFieldKeyReleased

    private void phoneNumFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneNumFieldKeyTyped
        String value = phoneNumField.getText();
        phoneNumField.setText(value.replaceAll("[^\\d]", ""));
    }//GEN-LAST:event_phoneNumFieldKeyTyped

    private void phoneNumFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneNumFieldKeyPressed
        String value = phoneNumField.getText();
        phoneNumField.setText(value.replaceAll("[^\\d]", ""));
    }//GEN-LAST:event_phoneNumFieldKeyPressed

    private void startMonthBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_startMonthBoxItemStateChanged
        if (evt.getItem() == "1" || evt.getItem() == "3" || evt.getItem() == "5" || evt.getItem() == "7" || evt.getItem() == "8" || evt.getItem() == "10" || evt.getItem() == "12") {
            String[] comboBoxItems = new String[32];
            comboBoxItems[0] = "Day";
            for (int i = 1; i < 32; i++) {
                comboBoxItems[i] = String.valueOf(i);
            }
            startDayBox.setModel(new javax.swing.DefaultComboBoxModel<>(comboBoxItems));
        } else if (evt.getItem() == "4" || evt.getItem() == "6" || evt.getItem() == "9" || evt.getItem() == "11") {
            String[] comboBoxItems = new String[31];
            comboBoxItems[0] = "Day";
            for (int i = 1; i < 31; i++) {
                comboBoxItems[i] = String.valueOf(i);
            }
            startDayBox.setModel(new javax.swing.DefaultComboBoxModel<>(comboBoxItems));
        } else {
            String[] comboBoxItems = new String[29];
            comboBoxItems[0] = "Day";
            for (int i = 1; i < 29; i++) {
                comboBoxItems[i] = String.valueOf(i);
            }
            startDayBox.setModel(new javax.swing.DefaultComboBoxModel<>(comboBoxItems));
        }
    }//GEN-LAST:event_startMonthBoxItemStateChanged

    private void endMonthBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_endMonthBoxItemStateChanged
        if (evt.getItem() == "1" || evt.getItem() == "3" || evt.getItem() == "5" || evt.getItem() == "7" || evt.getItem() == "8" || evt.getItem() == "10" || evt.getItem() == "12") {
            String[] comboBoxItems = new String[32];
            comboBoxItems[0] = "Day";
            for (int i = 1; i < 32; i++) {
                comboBoxItems[i] = String.valueOf(i);
            }
            endDayBox.setModel(new javax.swing.DefaultComboBoxModel<>(comboBoxItems));
        } else if (evt.getItem() == "4" || evt.getItem() == "6" || evt.getItem() == "9" || evt.getItem() == "11") {
            String[] comboBoxItems = new String[31];
            comboBoxItems[0] = "Day";
            for (int i = 1; i < 31; i++) {
                comboBoxItems[i] = String.valueOf(i);
            }
            endDayBox.setModel(new javax.swing.DefaultComboBoxModel<>(comboBoxItems));
        } else {
            String[] comboBoxItems = new String[29];
            comboBoxItems[0] = "Day";
            for (int i = 1; i < 29; i++) {
                comboBoxItems[i] = String.valueOf(i);
            }
            endDayBox.setModel(new javax.swing.DefaultComboBoxModel<>(comboBoxItems));
        }
    }//GEN-LAST:event_endMonthBoxItemStateChanged

    private void bookNowBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookNowBtnActionPerformed
        String hotelName = selectedHotelLabel.getText();
        String hotelAddress = selectedAddressLabel.getText();
        String roomType = null;
        Enumeration<AbstractButton> roomTypeBtns = RoomTypeBtnGroup.getElements();
        while (roomTypeBtns.hasMoreElements()) {
            AbstractButton modelbtn = roomTypeBtns.nextElement();
            if (modelbtn.isSelected()) {
                roomType = modelbtn.getText();
                break;
            }
        }
        if (roomType == null) {
            JOptionPane.showMessageDialog(this, "Please select one room type.       ", "Notice", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        int roomNum = Integer.parseInt((String) roomNumComboBox.getSelectedItem());
        int peopleNum = Integer.parseInt((String) peopleNumComboBox.getSelectedItem());
        //start date
        if (startYearBox.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Please select the start year.       ", "Notice", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        String startYear = (String) startYearBox.getSelectedItem();
        if (startMonthBox.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Please select the start month.       ", "Notice", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        String startMonth = (String) startMonthBox.getSelectedItem();
        if (startDayBox.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Please select the start day.       ", "Notice", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        String startDay = (String) startDayBox.getSelectedItem();
        //end date
        if (endYearBox.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Please select the end year.       ", "Notice", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        String endYear = (String) endYearBox.getSelectedItem();
        if (endMonthBox.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Please select the end month.       ", "Notice", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        String endMonth = (String) endMonthBox.getSelectedItem();
        if (endDayBox.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Please select the end day.       ", "Notice", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        String endDay = (String) endDayBox.getSelectedItem();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        Date startDate = new Date(Integer.parseInt(startYear) - 1900, Integer.parseInt(startMonth) - 1, Integer.parseInt(startDay));
        String formatStartDate = getDate(startDate);
        Date endDate = new Date(Integer.parseInt(endYear) - 1900, Integer.parseInt(endMonth) - 1, Integer.parseInt(endDay));
        String formatEndDate = getDate(endDate);
        if (startDate.before(today)) {
            JOptionPane.showMessageDialog(this, "The start date shouldn't before today.       ", "Notice", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        if (endDate.before(startDate)) {
            JOptionPane.showMessageDialog(this, "The end date should after start date.       ", "Notice", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        String bookerName = bookerNameField.getText();
        if (bookerName.equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter the booker name.       ", "Notice", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        String phoneNum = phoneNumField.getText();
        phoneNum = phoneNum.replaceAll("[^\\d]", "");
        if (phoneNum.equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter the phone number.       ", "Notice", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        if (phoneNum.length() != 11) {
            JOptionPane.showMessageDialog(this, "Please enter the correct phone number.       ", "Notice", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        int quitVal = JOptionPane.showConfirmDialog(this, "Do you want to submit this booking?", "Notice", JOptionPane.YES_NO_OPTION);
        if (quitVal == 0) {
            Booking booking = new Booking(hotelName, hotelAddress, roomType, roomNum, peopleNum, formatStartDate, formatEndDate, bookerName, phoneNum);
            bookings.add(booking);
            if (hotelName.equals("Green Hotel")) {
                if (roomType.equals("Single Room")) {
                    hotels[0].setRoom1Num(hotels[0].getRoom1Num() - roomNum);
                }
                if (roomType.equals("Double Room")) {
                    hotels[0].setRoom2Num(hotels[0].getRoom2Num() - roomNum);
                }
                if (roomType.equals("Standard Room")) {
                    hotels[0].setRoom3Num(hotels[0].getRoom3Num() - roomNum);
                }
            } else if (hotelName.equals("White Hotel")) {
                if (roomType.equals("Single Room")) {
                    hotels[1].setRoom1Num(hotels[1].getRoom1Num() - roomNum);
                }
                if (roomType.equals("Double Room")) {
                    hotels[1].setRoom2Num(hotels[1].getRoom2Num() - roomNum);
                }
                if (roomType.equals("Standard Room")) {
                    hotels[1].setRoom3Num(hotels[1].getRoom3Num() - roomNum);
                }
            }
            System.out.println(bookings.get(0).toString());
            System.out.println("Booking successfully");
            initBookingForm();
            JOptionPane.showMessageDialog(this, "Booking successfully. You can check your booking in \"My Reservation\".       ", "Notice", JOptionPane.INFORMATION_MESSAGE);
            bookingNow = 0;
            bookPanel.setVisible(true);
            hotelDetailPanel.setVisible(true);
        }
        if (quitVal == 1) {
            return;
        }


    }//GEN-LAST:event_bookNowBtnActionPerformed

    private void mapLabelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mapLabelMouseMoved
        Point point = evt.getLocationOnScreen();
        Point jFrameLocation = this.getLocation();
        if (point.x >= 306 + jFrameLocation.x && point.x <= 343 + jFrameLocation.x && point.y >= 255 + jFrameLocation.y && point.y <= 317 + jFrameLocation.y) {
            setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
            showImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/WhiteHotel.png")));
            showNameLabel.setText("White Hotel");
        } else if (point.x >= 506 + jFrameLocation.x && point.x <= 545 + jFrameLocation.x && point.y >= 333 + jFrameLocation.y && point.y <= 393 + jFrameLocation.y) {
            setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
            showImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/GreenHotel.png")));
            showNameLabel.setText("Green Hotel");
        } else {
            showImageLabel.setIcon(null);
            showNameLabel.setText(null);
            setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        }
    }//GEN-LAST:event_mapLabelMouseMoved

    private void mapLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mapLabelMouseClicked
        Point point = evt.getLocationOnScreen();
        Point jFrameLocation = this.getLocation();
        if (point.x >= 306 + jFrameLocation.x && point.x <= 343 + jFrameLocation.x && point.y >= 255 + jFrameLocation.y && point.y <= 317 + jFrameLocation.y) {
            if (bookingNow == 1 && selectedHotelLabel.getText().equals("Green Hotel")) {
                int quitVal = JOptionPane.showConfirmDialog(this, "Do you want to abandon this unfinished booking and view another hotel?", "Notice", JOptionPane.YES_NO_OPTION);
                if (quitVal == 0) {
                    loadHotelInfo(hotels[1]);
                    hotelDetailPanel.setVisible(true);
                    bookPanel.setVisible(true);
                    initBookingForm();
                    bookingNow = 0;
                }
            } else {
                loadHotelInfo(hotels[1]);
            }
            mapLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mapWhite.png")));

        } else if (point.x >= 506 + jFrameLocation.x && point.x <= 545 + jFrameLocation.x && point.y >= 333 + jFrameLocation.y && point.y <= 393 + jFrameLocation.y) {
            if (bookingNow == 1 && selectedHotelLabel.getText().equals("White Hotel")) {
                int quitVal = JOptionPane.showConfirmDialog(this, "Do you want to abandon this unfinished booking and view another hotel?", "Notice", JOptionPane.YES_NO_OPTION);
                if (quitVal == 0) {
                    loadHotelInfo(hotels[0]);
                    hotelDetailPanel.setVisible(true);
                    bookPanel.setVisible(true);
                    initBookingForm();
                    bookingNow = 0;
                }
            } else {
                loadHotelInfo(hotels[0]);
            }
            mapLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mapGreen.png")));
        }
    }//GEN-LAST:event_mapLabelMouseClicked

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        int quitVal = JOptionPane.showConfirmDialog(this, "Do you want to reset the booking information?", "Notice", JOptionPane.YES_NO_OPTION);
        if (quitVal == 0) {
            resetBookingForm();
        }
    }//GEN-LAST:event_resetBtnActionPerformed

    private void removeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBtnActionPerformed
        DefaultListModel defaultListModel = (DefaultListModel) bookingInfoList.getModel();
        if(bookingInfoList.getSelectedIndex() == -1){
            JOptionPane.showMessageDialog(this, "Please select a reservation before deleting.       ", "Notice", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        Booking booking = bookings.get(bookingInfoList.getSelectedIndex());
        if (booking.getHotelName().equals("Green Hotel")) {
            if (booking.getRoomType().equals("Single Room")) {
                hotels[0].setRoom1Num(hotels[0].getRoom1Num() + booking.getRoomNum());
            }
            if (booking.getRoomType().equals("Double Room")) {
                hotels[0].setRoom2Num(hotels[0].getRoom2Num() + booking.getRoomNum());
            }
            if (booking.getRoomType().equals("Standard Room")) {
                hotels[0].setRoom3Num(hotels[0].getRoom3Num() + booking.getRoomNum());
            }
        } else if (booking.getHotelName().equals("White Hotel")) {
            if (booking.getRoomType().equals("Single Room")) {
                hotels[1].setRoom1Num(hotels[1].getRoom1Num() + booking.getRoomNum());
            }
            if (booking.getRoomType().equals("Double Room")) {
                hotels[1].setRoom2Num(hotels[1].getRoom2Num() + booking.getRoomNum());
            }
            if (booking.getRoomType().equals("Standard Room")) {
                hotels[1].setRoom3Num(hotels[1].getRoom3Num() + booking.getRoomNum());
            }
        }
        bookings.remove(bookingInfoList.getSelectedIndex());
        defaultListModel.remove(bookingInfoList.getSelectedIndex());
        if (bookings.size() == 0) {
            totalBookingNumLabel.setText("You have no booking now");
        } else {
            totalBookingNumLabel.setText("You have " + bookings.size() + " booking totally");
        }
        JOptionPane.showMessageDialog(this, "Delete successfully.", "Notice", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_removeBtnActionPerformed

    private void DiscardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiscardActionPerformed
        int quitVal = JOptionPane.showConfirmDialog(this, "Do you want to discard the recent booking?", "Notice", JOptionPane.YES_NO_OPTION);
        if (quitVal == 0) {
            initBookingForm();
            hotelDetailPanel.setVisible(true);
            bookPanel.setVisible(true);
            bookingNow = 0;
        }
    }//GEN-LAST:event_DiscardActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HotelBookingSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HotelBookingSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HotelBookingSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HotelBookingSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        Locale.setDefault(Locale.ENGLISH);
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HotelBookingSystem().setVisible(true);
            }
        });
    }

    public String getDate() {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String date = sdf.format(new Date());
        return date;
    }

    public String getDate(Date date) {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String formatDate = sdf.format(date);
        return formatDate;
    }

    public void initBookingForm() {
        singleRoomBtn.setEnabled(true);
        doubleRoomBtn.setEnabled(true);
        standardRoomBtn.setEnabled(true);
        selectedHotelLabel.setText("");
        selectedAddressLabel.setText("");
        RoomTypeBtnGroup.clearSelection();
        roomNumComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{}));
        peopleNumComboBox.setSelectedIndex(0);
        startYearBox.setSelectedIndex(1);
        startMonthBox.setSelectedIndex(0);
        startDayBox.setSelectedIndex(0);
        endYearBox.setSelectedIndex(1);
        endMonthBox.setSelectedIndex(0);
        endDayBox.setSelectedIndex(0);
        bookerNameField.setText("");
        phoneNumField.setText("");
    }

    public void resetBookingForm() {

        RoomTypeBtnGroup.clearSelection();
        roomNumComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{}));
        peopleNumComboBox.setSelectedIndex(0);
        startYearBox.setSelectedIndex(1);
        startMonthBox.setSelectedIndex(0);
        startDayBox.setSelectedIndex(0);
        endYearBox.setSelectedIndex(1);
        endMonthBox.setSelectedIndex(0);
        endDayBox.setSelectedIndex(0);
        bookerNameField.setText("");
        phoneNumField.setText("");
    }

    public void loadHotelInfo(Hotel hotel) {
        hotelImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource(hotel.getHotelImg())));
        hotelNameLabel.setText(hotel.getName());
        hotelAddressLabel.setText(hotel.getAddress());
        favorableRateLabel.setText(String.valueOf(hotel.getFavorableRate()) + "%");
        room1Label.setIcon(new javax.swing.ImageIcon(getClass().getResource(hotel.getRoom1Img())));
        room2Label.setIcon(new javax.swing.ImageIcon(getClass().getResource(hotel.getRoom2Img())));
        room3Label.setIcon(new javax.swing.ImageIcon(getClass().getResource(hotel.getRoom3Img())));

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BookingBtn;
    private javax.swing.JButton Discard;
    private javax.swing.JButton ExitBtn;
    public javax.swing.ButtonGroup RoomTypeBtnGroup;
    public javax.swing.JButton bookBtn;
    private javax.swing.JButton bookNowBtn;
    public javax.swing.JPanel bookPanel;
    private javax.swing.JTextField bookerNameField;
    private javax.swing.JList<String> bookingInfoList;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JRadioButton doubleRoomBtn;
    private javax.swing.JComboBox<String> endDayBox;
    private javax.swing.JComboBox<String> endMonthBox;
    private javax.swing.JComboBox<String> endYearBox;
    private javax.swing.JLabel favorableRateLabel;
    private javax.swing.JButton helpBtn;
    private javax.swing.JLabel hotelAddressLabel;
    public javax.swing.JPanel hotelDetailPanel;
    public javax.swing.JLabel hotelImageLabel;
    public javax.swing.JLabel hotelNameLabel;
    private javax.swing.JPanel hotelPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public javax.swing.JLabel mapLabel;
    private javax.swing.JPanel myReservationPanel;
    private javax.swing.JPanel navigationBar;
    private javax.swing.JLabel noteLabel;
    private javax.swing.JComboBox<String> peopleNumComboBox;
    private javax.swing.JTextField phoneNumField;
    private javax.swing.JButton removeBtn;
    private javax.swing.JButton reservationBtn;
    private javax.swing.JButton resetBtn;
    private javax.swing.JLabel room1Label;
    private javax.swing.JLabel room1Num;
    public javax.swing.JLabel room2Label;
    private javax.swing.JLabel room2Num;
    private javax.swing.JLabel room3Label;
    private javax.swing.JLabel room3Num;
    private javax.swing.JComboBox<String> roomNumComboBox;
    public javax.swing.JLabel selectedAddressLabel;
    public javax.swing.JLabel selectedHotelLabel;
    public javax.swing.JLabel showImageLabel;
    public javax.swing.JLabel showNameLabel;
    private javax.swing.JRadioButton singleRoomBtn;
    private javax.swing.JRadioButton standardRoomBtn;
    private javax.swing.JComboBox<String> startDayBox;
    private javax.swing.JComboBox<String> startMonthBox;
    private javax.swing.JComboBox<String> startYearBox;
    public javax.swing.JLabel titleLabel;
    private javax.swing.ButtonGroup toolBarBtnGroup;
    private javax.swing.JLabel totalBookingNumLabel;
    // End of variables declaration//GEN-END:variables
}
